version: "3"

services:
  web:
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env.dev.docker

  mongodb:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data:
